[general]
import = ["./snazzy.toml"]

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
opacity = 0.8
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "Maple Mono NF CN", style = "Regular" }
size = 15

[cursor]
style = { blinking = "On" }
blink_timeout = 0
