[settings]
dotfiles.default_mode = "copy"

[dotfiles]
"~" = { source = "platform/common", exclude = [
  ".config/starship.toml",
  ".delta.gitconfig",
  ".gitconfig",
  ".gitignore_global",
] }
"~/.config/starship.toml" = { source = "platform/common/.config/starship.toml", mode = "template" }
"~/.delta.gitconfig" = { source = "platform/common/.delta.gitconfig", mode = "template" }
"~/.gitconfig" = { source = "platform/common/.gitconfig", mode = "template" }
"~/.gitignore_global" = { source = "platform/common/.gitignore_global", mode = "template" }
