"$schema" = "https://starship.rs/config-schema.json"

command_timeout = 300

[aws]
disabled = true

[custom.wsl]
shell = ["sh"]
when = "test -f /etc/wsl-distribution.conf"
format = "[in \ue70f wsl]($style) "
style = "bold yellow"
