unbind C-b
set -g prefix M-g
bind M-g send-prefix

bind R source-file ~/.tmux.conf \; display "Reloaded!"

set -s set-clipboard external

set -g mode-keys vi
set -g mouse on
set -g history-limit 10000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g status-interval 5
set -g status-right " %Y-%m-%d %H:%M "
