name: macOS

on:
  pull_request:
    paths:
      - .github/workflows/macos.yaml
      - lib/*.sh
      - platform/common/**
      - platform/macos/**
      - platform/unix/**
      - mise.macos.toml
      - mise.toml
      - mise.unix.toml
      - setup.sh
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/macos.yaml
      - lib/*.sh
      - platform/common/**
      - platform/macos/**
      - platform/unix/**
      - mise.macos.toml
      - mise.toml
      - mise.unix.toml
      - setup.sh
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup:
    runs-on: macos-latest
    timeout-minutes: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run setup.sh
        env:
          DF_CONFIG: 1
          DF_FISH: 1
        run: ./setup.sh

      - name: Check mise
        run: mise --version

      - name: Check dotfiles
        run: mise bootstrap dotfiles status --missing

      - name: Check default shell
        run: test "$(basename "$(dscl . -read "/Users/$USER" UserShell | awk '{print $2}')")" = fish
